### ISSUE TITLE
IndexError crash when parsing the response

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/aalto-sisu#1]
Crash `IndexError: list index out of range` on the line https://github.com/apluslms/aalto-sisu/blob/75c3fdae4aa15e538121c9e7d1e5787e1ae703a7/aalto_sisu/sis_aalto.py#L35

This doesn't look very serious, but fixing it should be easy. If the response JSON is empty or such, then don't try to index it. 

BTW, why is the response JSON empty (or is it)? The response status seems to be 200 OK since `response.raise_for_status()` did not raise any exception.

Traceback:
```
COURSE NAME: Error in getting participants from SIS.
Traceback (most recent call last):
  File "/a-plus/course/models.py", line 939, in enroll_from_sis
    participants = sis.get_participants(self.sis_id)
  File "/usr/local/lib/python3.8/dist-packages/aalto_sisu/sis_aalto.py", line 51, in get_participants
    json = self.request_from_enhanced_api(id)
  File "/usr/local/lib/python3.8/dist-packages/aalto_sisu/sis_aalto.py", line 35, in request_from_enhanced_api
    return response.json()[0]
IndexError: list index out of range
```

**Comment by markkuriekkinen** [comment]
@PasiSa for your information!
